const CHUNK_PUBLIC_PATH = "server/app/admin/page.js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_0962b827._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__fb250061._.js");
runtime.loadChunk("server/chunks/ssr/src_app_a4430781._.js");
runtime.loadChunk("server/chunks/ssr/_7cdb6043._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_96715ba7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_forbidden-error_ea7ea172.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_unauthorized-error_c8949b27.js");
runtime.loadChunk("server/chunks/ssr/node_modules_node-fetch_src_index_e19e703e.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_e6c0cf5d._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_a908d1ea._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_protobufjs_f8447822._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@firebase_firestore_dist_index_node_mjs_27b3c722._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_undici_b6bd72ee._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@firebase_storage_dist_node-esm_index_node_esm_95fda8cc.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@genkit-ai_core_lib_b4b8dea8._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_zod_lib_9973ecc6._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_ajv_dist_e6327f72._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_zod-to-json-schema_dist_cfb46992._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_core_build_esm_ac2e01f7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_semantic-conventions_build_esm_17a93919._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_resources_build_esm_eadd61b9._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_sdk-metrics_build_esm_2bc910b7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_sdk-trace-base_build_esm_ffb73884._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_otlp-transformer_build_esm_7b4c78bd._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_handlebars_097a2825._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_yaml_dist_5cbea403._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@genkit-ai_ai_lib_836f0c81._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@firebase_68bf1c72._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_371ac9f5._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_ca3b16ff._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__d7e17ec9._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/admin/page/actions.js { ACTIONS_MODULE0 => \"[project]/src/services/auth.service.ts [app-rsc] (ecmascript)\", ACTIONS_MODULE1 => \"[project]/src/services/gallery.service.ts [app-rsc] (ecmascript)\", ACTIONS_MODULE2 => \"[project]/src/app/actions.ts [app-rsc] (ecmascript)\", ACTIONS_MODULE3 => \"[project]/src/services/test.service.ts [app-rsc] (ecmascript)\" } [app-rsc] (server actions loader, ecmascript)", CHUNK_PUBLIC_PATH);
runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/src/app/admin/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/src/app/admin/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
